# clipboard
name: quote_master
description: A daily wisdom quote app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  flutter_spinkit: ^5.1.0
  intl: ^0.18.0
  clipboard: ^0.1.3
  share_plus: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # Add fonts if needed
  # fonts:
  #   - family: Arial
  #     fonts:
  #       - asset: assets/fonts/Arial-Regular.ttf
  #       - asset: assets/fonts/Arial-Bold.ttf
  #         weight: 700